name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install vcpkg
        shell: cmd
        run: |
          git clone https://github.com/microsoft/vcpkg C:\vcpkg
          C:\vcpkg\bootstrap-vcpkg.bat
          C:\vcpkg\vcpkg install curl:x64-windows
          C:\vcpkg\vcpkg install libzip:x64-windows

      - name: Configure
        shell: cmd
        run: |
          cmake -B build -A x64 ^
          -DCMAKE_TOOLCHAIN_FILE=C:\vcpkg\scripts\buildsystems\vcpkg.cmake

      - name: Build
        shell: cmd
        run: |
          cmake --build build --config Release

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Unlocker
          path: build/**/*.exe
