name: Build

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Clone vcpkg
        shell: pwsh
        run: |
          git clone https://github.com/microsoft/vcpkg.git C:\vcpkg
          & C:\vcpkg\bootstrap-vcpkg.bat

      - name: Install dependencies
        shell: pwsh
        run: |
          C:\vcpkg\vcpkg install zlib:x64-windows
          C:\vcpkg\vcpkg install curl:x64-windows
          C:\vcpkg\vcpkg install libzip:x64-windows

      - name: Configure
        shell: pwsh
        run: |
          cmake `
            -B build `
            -A x64 `
            -DCMAKE_TOOLCHAIN_FILE=C:\vcpkg\scripts\buildsystems\vcpkg.cmake

      - name: Build
        shell: pwsh
        run: |
          cmake --build build --config Release

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: Unlocker
          path: |
            build/**/*.exe
